### ISSUE TITLE
您好，来自车联网小白的善意。

### ISSUE THREAD

**Issue by liyongyong1020** [SpereShelde/Veins#1]
您好，我是做车联网这方面的学生，很感谢您的资料，让我在埋头研究的时候能够借鉴前辈的经验，少走很多弯路，非常感谢您。
然后看了一下您在github上的代码，只是魔改应用层version2的代码，没有version1的代码，对吗？
期待您的回复，学生不胜感激，祝您生活愉快。

**Comment by SpereShelde** [comment]
太久远了，我刚回顾了一下我的wiki，好像应该就是在src1下吧？

**Comment by liyongyong1020** [comment]
谢谢老师，大意了，没看其他分支。
祝您学业有成，生活愉快。

**Comment by SpereShelde** [comment]
没事，虽然我应该也没大你几岁哈哈
